// symbols.js — addresses, from the decompilation rather than from guessing.
//
// GENERATED by tools/gen-symbols.mjs from pret's published symbol files. Do not
// edit by hand; re-run the generator.
//
// An address that is merely plausible is worse than no address at all -- that
// is the whole reason this file exists rather than a list of constants found
// by searching RAM for the right shape. The one that was found that way and
// was wrong, `0x0203b0a8`, is nine bytes into `gPartyMenu`.

/** The cartridges these describe. Every RAM address below is identical across
 *  both published builds; only the code addresses differ, and those are given
 *  as a list so the running one can be recognised rather than assumed. */
export const FOR = ["BPRE", "BPRG"];

export const SYMBOLS = {
  /** a trainer battle cannot be fled; this says which it is */
  gBattleTypeFlags: 0x02022b4c,
  /** which party slot each battler is -- the one we had wrong */
  gBattlerPartyIndexes: 0x02023bce,
  /** FIGHT / BAG / POKéMON / RUN, as a two-bit grid */
  gActionSelectionCursor: 0x02023ff8,
  /** which of the four moves is under the cursor */
  gMoveSelectionCursor: 0x02023ffc,
  /** how many of them are real */
  gPlayerPartyCount: 0x02024029,
  /** the six hundred bytes the whole policy is judged from */
  gPlayerParty: 0x02024284,
  /** the generic menu cursor: position at +2, last valid index at +4. Every list menu in the field uses it, so nothing has to count its own presses */
  sMenu: 0x0203ade4,
  /** a pointer to the party menu's scratch struct. actions[] at +15 and numActions at +23 are the submenu entries as ids -- which is how the run can know SWITCH from ITEM instead of pressing A at both */
  sPartyMenuInternal: 0x0203b09c,
  /** slotId at +9 is the cursor, slotId2 at +10 is where a held Pokémon will go, action at +11 */
  gPartyMenu: 0x0203b0a0,
  /** TRUE while the game holds the controls -- a script, a cutscene, or a message box. Every freeze reported so far is this byte being set while the walk pressed directions at it */
  sLockFieldControls: 0x03000f9c,
  /** per-frame bookkeeping; the in-battle flag lives in its flags */
  gMain: 0x030030f0,
  /** a function pointer that *is* the battle's state: one address while the action menu waits for input, another while the move list does */
  gBattlerControllerFuncs: 0x03004fe0,
  /** SaveBlock1, which holds the position and the last heal */
  gSaveBlock1Ptr: 0x03005008,
  /** the action menu is up */
  HandleInputChooseAction: [0x0802e439, 0x0802e44d],
  /** the move list is up */
  HandleInputChooseMove: [0x0802ea11, 0x0802ea25],
  /** the in-battle party menu is up */
  WaitForMonSelection: [0x08030685, 0x08030699],
};

/** `gPartyMenu.slotId` — the party cursor, nine bytes into the struct. */
export const PARTY_MENU_SLOT = SYMBOLS.gPartyMenu + 9;
