// The original 151, with the handful of facts the questions are asked about.
//
// Generated from PokeAPI's static data mirror (github.com/PokeAPI/api-data) and
// its official-artwork sprites (github.com/PokeAPI/sprites), which are trimmed
// and re-encoded to 256px WebP in assets/art/<id>.webp — about 16 KB each, so a
// full board of 24 costs roughly 380 KB and the whole set 2.4 MB.
//
// Every field here is something a question can turn on, which is why the list is
// baked in rather than fetched: an answer has to be computable offline, on both
// devices, from data that cannot disagree between them.
//
//   stage    1 basic, 2 first evolution, 3 second — counted *within* these 151,
//            so Pikachu is a basic (Pichu is a later generation) and Golbat is
//            final (Crobat is too).
//   evolves  true if something in these 151 evolves from it.
//   height   metres.  weight  kilograms.
export const POKEMON = [
  {id: 1, name: "Bulbasaur", types: ["grass", "poison"], color: "green", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.7, weight: 6.9, stage: 1, evolves: true},
  {id: 2, name: "Ivysaur", types: ["grass", "poison"], color: "green", shape: "quadruped", habitat: "grassland", legendary: false, height: 1, weight: 13, stage: 2, evolves: true},
  {id: 3, name: "Venusaur", types: ["grass", "poison"], color: "green", shape: "quadruped", habitat: "grassland", legendary: false, height: 2, weight: 100, stage: 3, evolves: false},
  {id: 4, name: "Charmander", types: ["fire"], color: "red", shape: "upright", habitat: "mountain", legendary: false, height: 0.6, weight: 8.5, stage: 1, evolves: true},
  {id: 5, name: "Charmeleon", types: ["fire"], color: "red", shape: "upright", habitat: "mountain", legendary: false, height: 1.1, weight: 19, stage: 2, evolves: true},
  {id: 6, name: "Charizard", types: ["fire", "flying"], color: "red", shape: "upright", habitat: "mountain", legendary: false, height: 1.7, weight: 90.5, stage: 3, evolves: false},
  {id: 7, name: "Squirtle", types: ["water"], color: "blue", shape: "upright", habitat: "waters-edge", legendary: false, height: 0.5, weight: 9, stage: 1, evolves: true},
  {id: 8, name: "Wartortle", types: ["water"], color: "blue", shape: "upright", habitat: "waters-edge", legendary: false, height: 1, weight: 22.5, stage: 2, evolves: true},
  {id: 9, name: "Blastoise", types: ["water"], color: "blue", shape: "upright", habitat: "waters-edge", legendary: false, height: 1.6, weight: 85.5, stage: 3, evolves: false},
  {id: 10, name: "Caterpie", types: ["bug"], color: "green", shape: "armor", habitat: "forest", legendary: false, height: 0.3, weight: 2.9, stage: 1, evolves: true},
  {id: 11, name: "Metapod", types: ["bug"], color: "green", shape: "squiggle", habitat: "forest", legendary: false, height: 0.7, weight: 9.9, stage: 2, evolves: true},
  {id: 12, name: "Butterfree", types: ["bug", "flying"], color: "white", shape: "bug-wings", habitat: "forest", legendary: false, height: 1.1, weight: 32, stage: 3, evolves: false},
  {id: 13, name: "Weedle", types: ["bug", "poison"], color: "brown", shape: "armor", habitat: "forest", legendary: false, height: 0.3, weight: 3.2, stage: 1, evolves: true},
  {id: 14, name: "Kakuna", types: ["bug", "poison"], color: "yellow", shape: "squiggle", habitat: "forest", legendary: false, height: 0.6, weight: 10, stage: 2, evolves: true},
  {id: 15, name: "Beedrill", types: ["bug", "poison"], color: "yellow", shape: "bug-wings", habitat: "forest", legendary: false, height: 1, weight: 29.5, stage: 3, evolves: false},
  {id: 16, name: "Pidgey", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "forest", legendary: false, height: 0.3, weight: 1.8, stage: 1, evolves: true},
  {id: 17, name: "Pidgeotto", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "forest", legendary: false, height: 1.1, weight: 30, stage: 2, evolves: true},
  {id: 18, name: "Pidgeot", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "forest", legendary: false, height: 1.5, weight: 39.5, stage: 3, evolves: false},
  {id: 19, name: "Rattata", types: ["normal"], color: "purple", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.3, weight: 3.5, stage: 1, evolves: true},
  {id: 20, name: "Raticate", types: ["normal"], color: "brown", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.7, weight: 18.5, stage: 2, evolves: false},
  {id: 21, name: "Spearow", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "rough-terrain", legendary: false, height: 0.3, weight: 2, stage: 1, evolves: true},
  {id: 22, name: "Fearow", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "rough-terrain", legendary: false, height: 1.2, weight: 38, stage: 2, evolves: false},
  {id: 23, name: "Ekans", types: ["poison"], color: "purple", shape: "squiggle", habitat: "grassland", legendary: false, height: 2, weight: 6.9, stage: 1, evolves: true},
  {id: 24, name: "Arbok", types: ["poison"], color: "purple", shape: "squiggle", habitat: "grassland", legendary: false, height: 3.5, weight: 65, stage: 2, evolves: false},
  {id: 25, name: "Pikachu", types: ["electric"], color: "yellow", shape: "quadruped", habitat: "forest", legendary: false, height: 0.4, weight: 6, stage: 1, evolves: true},
  {id: 26, name: "Raichu", types: ["electric"], color: "yellow", shape: "upright", habitat: "forest", legendary: false, height: 0.8, weight: 30, stage: 2, evolves: false},
  {id: 27, name: "Sandshrew", types: ["ground"], color: "yellow", shape: "upright", habitat: "rough-terrain", legendary: false, height: 0.6, weight: 12, stage: 1, evolves: true},
  {id: 28, name: "Sandslash", types: ["ground"], color: "yellow", shape: "upright", habitat: "rough-terrain", legendary: false, height: 1, weight: 29.5, stage: 2, evolves: false},
  {id: 29, name: "Nidoran♀", types: ["poison"], color: "blue", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.4, weight: 7, stage: 1, evolves: true},
  {id: 30, name: "Nidorina", types: ["poison"], color: "blue", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.8, weight: 20, stage: 2, evolves: true},
  {id: 31, name: "Nidoqueen", types: ["poison", "ground"], color: "blue", shape: "upright", habitat: "grassland", legendary: false, height: 1.3, weight: 60, stage: 3, evolves: false},
  {id: 32, name: "Nidoran♂", types: ["poison"], color: "purple", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.5, weight: 9, stage: 1, evolves: true},
  {id: 33, name: "Nidorino", types: ["poison"], color: "purple", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.9, weight: 19.5, stage: 2, evolves: true},
  {id: 34, name: "Nidoking", types: ["poison", "ground"], color: "purple", shape: "upright", habitat: "grassland", legendary: false, height: 1.4, weight: 62, stage: 3, evolves: false},
  {id: 35, name: "Clefairy", types: ["fairy"], color: "pink", shape: "upright", habitat: "mountain", legendary: false, height: 0.6, weight: 7.5, stage: 1, evolves: true},
  {id: 36, name: "Clefable", types: ["fairy"], color: "pink", shape: "upright", habitat: "mountain", legendary: false, height: 1.3, weight: 40, stage: 2, evolves: false},
  {id: 37, name: "Vulpix", types: ["fire"], color: "brown", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.6, weight: 9.9, stage: 1, evolves: true},
  {id: 38, name: "Ninetales", types: ["fire"], color: "yellow", shape: "quadruped", habitat: "grassland", legendary: false, height: 1.1, weight: 19.9, stage: 2, evolves: false},
  {id: 39, name: "Jigglypuff", types: ["normal", "fairy"], color: "pink", shape: "humanoid", habitat: "grassland", legendary: false, height: 0.5, weight: 5.5, stage: 1, evolves: true},
  {id: 40, name: "Wigglytuff", types: ["normal", "fairy"], color: "pink", shape: "humanoid", habitat: "grassland", legendary: false, height: 1, weight: 12, stage: 2, evolves: false},
  {id: 41, name: "Zubat", types: ["poison", "flying"], color: "purple", shape: "wings", habitat: "cave", legendary: false, height: 0.8, weight: 7.5, stage: 1, evolves: true},
  {id: 42, name: "Golbat", types: ["poison", "flying"], color: "purple", shape: "wings", habitat: "cave", legendary: false, height: 1.6, weight: 55, stage: 2, evolves: false},
  {id: 43, name: "Oddish", types: ["grass", "poison"], color: "blue", shape: "legs", habitat: "grassland", legendary: false, height: 0.5, weight: 5.4, stage: 1, evolves: true},
  {id: 44, name: "Gloom", types: ["grass", "poison"], color: "blue", shape: "humanoid", habitat: "grassland", legendary: false, height: 0.8, weight: 8.6, stage: 2, evolves: true},
  {id: 45, name: "Vileplume", types: ["grass", "poison"], color: "red", shape: "humanoid", habitat: "grassland", legendary: false, height: 1.2, weight: 18.6, stage: 3, evolves: false},
  {id: 46, name: "Paras", types: ["bug", "grass"], color: "red", shape: "armor", habitat: "forest", legendary: false, height: 0.3, weight: 5.4, stage: 1, evolves: true},
  {id: 47, name: "Parasect", types: ["bug", "grass"], color: "red", shape: "armor", habitat: "forest", legendary: false, height: 1, weight: 29.5, stage: 2, evolves: false},
  {id: 48, name: "Venonat", types: ["bug", "poison"], color: "purple", shape: "humanoid", habitat: "forest", legendary: false, height: 1, weight: 30, stage: 1, evolves: true},
  {id: 49, name: "Venomoth", types: ["bug", "poison"], color: "purple", shape: "bug-wings", habitat: "forest", legendary: false, height: 1.5, weight: 12.5, stage: 2, evolves: false},
  {id: 50, name: "Diglett", types: ["ground"], color: "brown", shape: "blob", habitat: "cave", legendary: false, height: 0.2, weight: 0.8, stage: 1, evolves: true},
  {id: 51, name: "Dugtrio", types: ["ground"], color: "brown", shape: "heads", habitat: "cave", legendary: false, height: 0.7, weight: 33.3, stage: 2, evolves: false},
  {id: 52, name: "Meowth", types: ["normal"], color: "yellow", shape: "quadruped", habitat: "urban", legendary: false, height: 0.4, weight: 4.2, stage: 1, evolves: true},
  {id: 53, name: "Persian", types: ["normal"], color: "yellow", shape: "quadruped", habitat: "urban", legendary: false, height: 1, weight: 32, stage: 2, evolves: false},
  {id: 54, name: "Psyduck", types: ["water"], color: "yellow", shape: "upright", habitat: "waters-edge", legendary: false, height: 0.8, weight: 19.6, stage: 1, evolves: true},
  {id: 55, name: "Golduck", types: ["water"], color: "blue", shape: "upright", habitat: "waters-edge", legendary: false, height: 1.7, weight: 76.6, stage: 2, evolves: false},
  {id: 56, name: "Mankey", types: ["fighting"], color: "brown", shape: "upright", habitat: "mountain", legendary: false, height: 0.5, weight: 28, stage: 1, evolves: true},
  {id: 57, name: "Primeape", types: ["fighting"], color: "brown", shape: "upright", habitat: "mountain", legendary: false, height: 1, weight: 32, stage: 2, evolves: false},
  {id: 58, name: "Growlithe", types: ["fire"], color: "brown", shape: "quadruped", habitat: "grassland", legendary: false, height: 0.7, weight: 19, stage: 1, evolves: true},
  {id: 59, name: "Arcanine", types: ["fire"], color: "brown", shape: "quadruped", habitat: "grassland", legendary: false, height: 1.9, weight: 155, stage: 2, evolves: false},
  {id: 60, name: "Poliwag", types: ["water"], color: "blue", shape: "legs", habitat: "waters-edge", legendary: false, height: 0.6, weight: 12.4, stage: 1, evolves: true},
  {id: 61, name: "Poliwhirl", types: ["water"], color: "blue", shape: "humanoid", habitat: "waters-edge", legendary: false, height: 1, weight: 20, stage: 2, evolves: true},
  {id: 62, name: "Poliwrath", types: ["water", "fighting"], color: "blue", shape: "humanoid", habitat: "waters-edge", legendary: false, height: 1.3, weight: 54, stage: 3, evolves: false},
  {id: 63, name: "Abra", types: ["psychic"], color: "brown", shape: "upright", habitat: "urban", legendary: false, height: 0.9, weight: 19.5, stage: 1, evolves: true},
  {id: 64, name: "Kadabra", types: ["psychic"], color: "brown", shape: "upright", habitat: "urban", legendary: false, height: 1.3, weight: 56.5, stage: 2, evolves: true},
  {id: 65, name: "Alakazam", types: ["psychic"], color: "brown", shape: "humanoid", habitat: "urban", legendary: false, height: 1.5, weight: 48, stage: 3, evolves: false},
  {id: 66, name: "Machop", types: ["fighting"], color: "gray", shape: "upright", habitat: "mountain", legendary: false, height: 0.8, weight: 19.5, stage: 1, evolves: true},
  {id: 67, name: "Machoke", types: ["fighting"], color: "gray", shape: "humanoid", habitat: "mountain", legendary: false, height: 1.5, weight: 70.5, stage: 2, evolves: true},
  {id: 68, name: "Machamp", types: ["fighting"], color: "gray", shape: "humanoid", habitat: "mountain", legendary: false, height: 1.6, weight: 130, stage: 3, evolves: false},
  {id: 69, name: "Bellsprout", types: ["grass", "poison"], color: "green", shape: "humanoid", habitat: "forest", legendary: false, height: 0.7, weight: 4, stage: 1, evolves: true},
  {id: 70, name: "Weepinbell", types: ["grass", "poison"], color: "green", shape: "blob", habitat: "forest", legendary: false, height: 1, weight: 6.4, stage: 2, evolves: true},
  {id: 71, name: "Victreebel", types: ["grass", "poison"], color: "green", shape: "blob", habitat: "forest", legendary: false, height: 1.7, weight: 15.5, stage: 3, evolves: false},
  {id: 72, name: "Tentacool", types: ["water", "poison"], color: "blue", shape: "tentacles", habitat: "sea", legendary: false, height: 0.9, weight: 45.5, stage: 1, evolves: true},
  {id: 73, name: "Tentacruel", types: ["water", "poison"], color: "blue", shape: "tentacles", habitat: "sea", legendary: false, height: 1.6, weight: 55, stage: 2, evolves: false},
  {id: 74, name: "Geodude", types: ["rock", "ground"], color: "brown", shape: "arms", habitat: "mountain", legendary: false, height: 0.4, weight: 20, stage: 1, evolves: true},
  {id: 75, name: "Graveler", types: ["rock", "ground"], color: "brown", shape: "humanoid", habitat: "mountain", legendary: false, height: 1, weight: 105, stage: 2, evolves: true},
  {id: 76, name: "Golem", types: ["rock", "ground"], color: "brown", shape: "humanoid", habitat: "mountain", legendary: false, height: 1.4, weight: 300, stage: 3, evolves: false},
  {id: 77, name: "Ponyta", types: ["fire"], color: "yellow", shape: "quadruped", habitat: "grassland", legendary: false, height: 1, weight: 30, stage: 1, evolves: true},
  {id: 78, name: "Rapidash", types: ["fire"], color: "yellow", shape: "quadruped", habitat: "grassland", legendary: false, height: 1.7, weight: 95, stage: 2, evolves: false},
  {id: 79, name: "Slowpoke", types: ["water", "psychic"], color: "pink", shape: "quadruped", habitat: "waters-edge", legendary: false, height: 1.2, weight: 36, stage: 1, evolves: true},
  {id: 80, name: "Slowbro", types: ["water", "psychic"], color: "pink", shape: "upright", habitat: "waters-edge", legendary: false, height: 1.6, weight: 78.5, stage: 2, evolves: false},
  {id: 81, name: "Magnemite", types: ["electric", "steel"], color: "gray", shape: "arms", habitat: "rough-terrain", legendary: false, height: 0.3, weight: 6, stage: 1, evolves: true},
  {id: 82, name: "Magneton", types: ["electric", "steel"], color: "gray", shape: "heads", habitat: "rough-terrain", legendary: false, height: 1, weight: 60, stage: 2, evolves: false},
  {id: 83, name: "Farfetch’d", types: ["normal", "flying"], color: "brown", shape: "wings", habitat: "grassland", legendary: false, height: 0.8, weight: 15, stage: 1, evolves: false},
  {id: 84, name: "Doduo", types: ["normal", "flying"], color: "brown", shape: "legs", habitat: "grassland", legendary: false, height: 1.4, weight: 39.2, stage: 1, evolves: true},
  {id: 85, name: "Dodrio", types: ["normal", "flying"], color: "brown", shape: "legs", habitat: "grassland", legendary: false, height: 1.8, weight: 85.2, stage: 2, evolves: false},
  {id: 86, name: "Seel", types: ["water"], color: "white", shape: "fish", habitat: "sea", legendary: false, height: 1.1, weight: 90, stage: 1, evolves: true},
  {id: 87, name: "Dewgong", types: ["water", "ice"], color: "white", shape: "fish", habitat: "sea", legendary: false, height: 1.7, weight: 120, stage: 2, evolves: false},
  {id: 88, name: "Grimer", types: ["poison"], color: "purple", shape: "arms", habitat: "urban", legendary: false, height: 0.9, weight: 30, stage: 1, evolves: true},
  {id: 89, name: "Muk", types: ["poison"], color: "purple", shape: "arms", habitat: "urban", legendary: false, height: 1.2, weight: 30, stage: 2, evolves: false},
  {id: 90, name: "Shellder", types: ["water"], color: "purple", shape: "ball", habitat: "sea", legendary: false, height: 0.3, weight: 4, stage: 1, evolves: true},
  {id: 91, name: "Cloyster", types: ["water", "ice"], color: "purple", shape: "ball", habitat: "sea", legendary: false, height: 1.5, weight: 132.5, stage: 2, evolves: false},
  {id: 92, name: "Gastly", types: ["ghost", "poison"], color: "purple", shape: "ball", habitat: "cave", legendary: false, height: 1.3, weight: 0.1, stage: 1, evolves: true},
  {id: 93, name: "Haunter", types: ["ghost", "poison"], color: "purple", shape: "arms", habitat: "cave", legendary: false, height: 1.6, weight: 0.1, stage: 2, evolves: true},
  {id: 94, name: "Gengar", types: ["ghost", "poison"], color: "purple", shape: "upright", habitat: "cave", legendary: false, height: 1.5, weight: 40.5, stage: 3, evolves: false},
  {id: 95, name: "Onix", types: ["rock", "ground"], color: "gray", shape: "squiggle", habitat: "cave", legendary: false, height: 8.8, weight: 210, stage: 1, evolves: false},
  {id: 96, name: "Drowzee", types: ["psychic"], color: "yellow", shape: "humanoid", habitat: "grassland", legendary: false, height: 1, weight: 32.4, stage: 1, evolves: true},
  {id: 97, name: "Hypno", types: ["psychic"], color: "yellow", shape: "humanoid", habitat: "grassland", legendary: false, height: 1.6, weight: 75.6, stage: 2, evolves: false},
  {id: 98, name: "Krabby", types: ["water"], color: "red", shape: "armor", habitat: "waters-edge", legendary: false, height: 0.4, weight: 6.5, stage: 1, evolves: true},
  {id: 99, name: "Kingler", types: ["water"], color: "red", shape: "armor", habitat: "waters-edge", legendary: false, height: 1.3, weight: 60, stage: 2, evolves: false},
  {id: 100, name: "Voltorb", types: ["electric"], color: "red", shape: "ball", habitat: "urban", legendary: false, height: 0.5, weight: 10.4, stage: 1, evolves: true},
  {id: 101, name: "Electrode", types: ["electric"], color: "red", shape: "ball", habitat: "urban", legendary: false, height: 1.2, weight: 66.6, stage: 2, evolves: false},
  {id: 102, name: "Exeggcute", types: ["grass", "psychic"], color: "pink", shape: "heads", habitat: "forest", legendary: false, height: 0.4, weight: 2.5, stage: 1, evolves: true},
  {id: 103, name: "Exeggutor", types: ["grass", "psychic"], color: "yellow", shape: "legs", habitat: "forest", legendary: false, height: 2, weight: 120, stage: 2, evolves: false},
  {id: 104, name: "Cubone", types: ["ground"], color: "brown", shape: "upright", habitat: "mountain", legendary: false, height: 0.4, weight: 6.5, stage: 1, evolves: true},
  {id: 105, name: "Marowak", types: ["ground"], color: "brown", shape: "upright", habitat: "mountain", legendary: false, height: 1, weight: 45, stage: 2, evolves: false},
  {id: 106, name: "Hitmonlee", types: ["fighting"], color: "brown", shape: "humanoid", habitat: "urban", legendary: false, height: 1.5, weight: 49.8, stage: 1, evolves: false},
  {id: 107, name: "Hitmonchan", types: ["fighting"], color: "brown", shape: "humanoid", habitat: "urban", legendary: false, height: 1.4, weight: 50.2, stage: 1, evolves: false},
  {id: 108, name: "Lickitung", types: ["normal"], color: "pink", shape: "upright", habitat: "grassland", legendary: false, height: 1.2, weight: 65.5, stage: 1, evolves: false},
  {id: 109, name: "Koffing", types: ["poison"], color: "purple", shape: "ball", habitat: "urban", legendary: false, height: 0.6, weight: 1, stage: 1, evolves: true},
  {id: 110, name: "Weezing", types: ["poison"], color: "purple", shape: "heads", habitat: "urban", legendary: false, height: 1.2, weight: 9.5, stage: 2, evolves: false},
  {id: 111, name: "Rhyhorn", types: ["ground", "rock"], color: "gray", shape: "quadruped", habitat: "rough-terrain", legendary: false, height: 1, weight: 115, stage: 1, evolves: true},
  {id: 112, name: "Rhydon", types: ["ground", "rock"], color: "gray", shape: "upright", habitat: "rough-terrain", legendary: false, height: 1.9, weight: 120, stage: 2, evolves: false},
  {id: 113, name: "Chansey", types: ["normal"], color: "pink", shape: "upright", habitat: "urban", legendary: false, height: 1.1, weight: 34.6, stage: 1, evolves: false},
  {id: 114, name: "Tangela", types: ["grass"], color: "blue", shape: "legs", habitat: "grassland", legendary: false, height: 1, weight: 35, stage: 1, evolves: false},
  {id: 115, name: "Kangaskhan", types: ["normal"], color: "brown", shape: "upright", habitat: "grassland", legendary: false, height: 2.2, weight: 80, stage: 1, evolves: false},
  {id: 116, name: "Horsea", types: ["water"], color: "blue", shape: "blob", habitat: "sea", legendary: false, height: 0.4, weight: 8, stage: 1, evolves: true},
  {id: 117, name: "Seadra", types: ["water"], color: "blue", shape: "blob", habitat: "sea", legendary: false, height: 1.2, weight: 25, stage: 2, evolves: false},
  {id: 118, name: "Goldeen", types: ["water"], color: "red", shape: "fish", habitat: "waters-edge", legendary: false, height: 0.6, weight: 15, stage: 1, evolves: true},
  {id: 119, name: "Seaking", types: ["water"], color: "red", shape: "fish", habitat: "waters-edge", legendary: false, height: 1.3, weight: 39, stage: 2, evolves: false},
  {id: 120, name: "Staryu", types: ["water"], color: "brown", shape: "blob", habitat: "sea", legendary: false, height: 0.8, weight: 34.5, stage: 1, evolves: true},
  {id: 121, name: "Starmie", types: ["water", "psychic"], color: "purple", shape: "blob", habitat: "sea", legendary: false, height: 1.1, weight: 80, stage: 2, evolves: false},
  {id: 122, name: "Mr. Mime", types: ["psychic", "fairy"], color: "pink", shape: "humanoid", habitat: "urban", legendary: false, height: 1.3, weight: 54.5, stage: 1, evolves: false},
  {id: 123, name: "Scyther", types: ["bug", "flying"], color: "green", shape: "bug-wings", habitat: "grassland", legendary: false, height: 1.5, weight: 56, stage: 1, evolves: false},
  {id: 124, name: "Jynx", types: ["ice", "psychic"], color: "red", shape: "humanoid", habitat: "urban", legendary: false, height: 1.4, weight: 40.6, stage: 1, evolves: false},
  {id: 125, name: "Electabuzz", types: ["electric"], color: "yellow", shape: "upright", habitat: "grassland", legendary: false, height: 1.1, weight: 30, stage: 1, evolves: false},
  {id: 126, name: "Magmar", types: ["fire"], color: "red", shape: "upright", habitat: "mountain", legendary: false, height: 1.3, weight: 44.5, stage: 1, evolves: false},
  {id: 127, name: "Pinsir", types: ["bug"], color: "brown", shape: "humanoid", habitat: "forest", legendary: false, height: 1.5, weight: 55, stage: 1, evolves: false},
  {id: 128, name: "Tauros", types: ["normal"], color: "brown", shape: "quadruped", habitat: "grassland", legendary: false, height: 1.4, weight: 88.4, stage: 1, evolves: false},
  {id: 129, name: "Magikarp", types: ["water"], color: "red", shape: "fish", habitat: "waters-edge", legendary: false, height: 0.9, weight: 10, stage: 1, evolves: true},
  {id: 130, name: "Gyarados", types: ["water", "flying"], color: "blue", shape: "squiggle", habitat: "waters-edge", legendary: false, height: 6.5, weight: 235, stage: 2, evolves: false},
  {id: 131, name: "Lapras", types: ["water", "ice"], color: "blue", shape: "fish", habitat: "sea", legendary: false, height: 2.5, weight: 220, stage: 1, evolves: false},
  {id: 132, name: "Ditto", types: ["normal"], color: "purple", shape: "ball", habitat: "urban", legendary: false, height: 0.3, weight: 4, stage: 1, evolves: false},
  {id: 133, name: "Eevee", types: ["normal"], color: "brown", shape: "quadruped", habitat: "urban", legendary: false, height: 0.3, weight: 6.5, stage: 1, evolves: true},
  {id: 134, name: "Vaporeon", types: ["water"], color: "blue", shape: "quadruped", habitat: "urban", legendary: false, height: 1, weight: 29, stage: 2, evolves: false},
  {id: 135, name: "Jolteon", types: ["electric"], color: "yellow", shape: "quadruped", habitat: "urban", legendary: false, height: 0.8, weight: 24.5, stage: 2, evolves: false},
  {id: 136, name: "Flareon", types: ["fire"], color: "red", shape: "quadruped", habitat: "urban", legendary: false, height: 0.9, weight: 25, stage: 2, evolves: false},
  {id: 137, name: "Porygon", types: ["normal"], color: "pink", shape: "legs", habitat: "urban", legendary: false, height: 0.8, weight: 36.5, stage: 1, evolves: false},
  {id: 138, name: "Omanyte", types: ["rock", "water"], color: "blue", shape: "tentacles", habitat: "sea", legendary: false, height: 0.4, weight: 7.5, stage: 1, evolves: true},
  {id: 139, name: "Omastar", types: ["rock", "water"], color: "blue", shape: "tentacles", habitat: "sea", legendary: false, height: 1, weight: 35, stage: 2, evolves: false},
  {id: 140, name: "Kabuto", types: ["rock", "water"], color: "brown", shape: "armor", habitat: "sea", legendary: false, height: 0.5, weight: 11.5, stage: 1, evolves: true},
  {id: 141, name: "Kabutops", types: ["rock", "water"], color: "brown", shape: "upright", habitat: "sea", legendary: false, height: 1.3, weight: 40.5, stage: 2, evolves: false},
  {id: 142, name: "Aerodactyl", types: ["rock", "flying"], color: "purple", shape: "wings", habitat: "mountain", legendary: false, height: 1.8, weight: 59, stage: 1, evolves: false},
  {id: 143, name: "Snorlax", types: ["normal"], color: "black", shape: "humanoid", habitat: "mountain", legendary: false, height: 2.1, weight: 460, stage: 1, evolves: false},
  {id: 144, name: "Articuno", types: ["ice", "flying"], color: "blue", shape: "wings", habitat: "rare", legendary: true, height: 1.7, weight: 55.4, stage: 1, evolves: false},
  {id: 145, name: "Zapdos", types: ["electric", "flying"], color: "yellow", shape: "wings", habitat: "rare", legendary: true, height: 1.6, weight: 52.6, stage: 1, evolves: false},
  {id: 146, name: "Moltres", types: ["fire", "flying"], color: "yellow", shape: "wings", habitat: "rare", legendary: true, height: 2, weight: 60, stage: 1, evolves: false},
  {id: 147, name: "Dratini", types: ["dragon"], color: "blue", shape: "squiggle", habitat: "waters-edge", legendary: false, height: 1.8, weight: 3.3, stage: 1, evolves: true},
  {id: 148, name: "Dragonair", types: ["dragon"], color: "blue", shape: "squiggle", habitat: "waters-edge", legendary: false, height: 4, weight: 16.5, stage: 2, evolves: true},
  {id: 149, name: "Dragonite", types: ["dragon", "flying"], color: "brown", shape: "upright", habitat: "waters-edge", legendary: false, height: 2.2, weight: 210, stage: 3, evolves: false},
  {id: 150, name: "Mewtwo", types: ["psychic"], color: "purple", shape: "upright", habitat: "rare", legendary: true, height: 2, weight: 122, stage: 1, evolves: false},
  {id: 151, name: "Mew", types: ["psychic"], color: "pink", shape: "upright", habitat: "rare", legendary: true, height: 0.4, weight: 4, stage: 1, evolves: false},
];
